#!/bin/bash

set -o errexit
set -o nounset

if [ $# -eq 0 ]
  then
    echo "Usage: run_automappa <path/to/recursive_dbscan_output.tab>"
    exit 0
fi

if [[ "$*" == *-h* ]];then
    docker run --detach=false --rm evanrees/automappa:latest -h
    exit 0
fi

LOCAL_PORT=8050
CONTAINER_PORT=8886

echo ":================== NOTICE ====================:"
echo
echo "Attention Automappa User: IGNORE Dash port ${CONTAINER_PORT}."
echo "Navigate to ---> http://localhost:${LOCAL_PORT}"
echo
echo ":----------------------------------------------:"

docker run \
    --publish $LOCAL_PORT:$CONTAINER_PORT \
    --detach=false \
    --rm \
    evanrees/automappa:latest --input $1 --port $CONTAINER_PORT --host 0.0.0.0
